### ISSUE TITLE
Make number of rows in Releases Table configureable

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-ocds#38] opened 2020-05-07 11:14 UTC
This should be configureable as an environment variable.

From https://github.com/open-contracting/cove-ocds/pull/35#issuecomment-624772641

**Comment by Bjwebb** [comment] 2020-05-07 12:48
![](https://github.trello.services/images/mini-trello-icon.png) [Quick fixes for large files](https://trello.com/c/pZJldiNG/70-quick-fixes-for-large-files)

**Comment by robredpath** [comment] 2020-05-28 09:33
![](https://github.trello.services/images/mini-trello-icon.png) [Make the number of rows in the records table configurable + document process](https://trello.com/c/ZO4mOka4/79-make-the-number-of-rows-in-the-records-table-configurable-document-process)

**Comment by jpmckinney** [comment] 2020-06-24 14:09
Is #31 then a duplicate of this issue?

**Comment by Bjwebb** [comment] 2020-06-25 15:10
I think they're separate issues, because this is about the releases table, whereas https://github.com/open-contracting/cove-ocds/issues/31#issuecomment-624775427 talks validation errors.

**Comment by jpmckinney** [comment] 2020-06-25 16:09
Okay, let's add #31 to the board, since it doesn't have a card.

**Closed** 2020-08-04 13:44 UTC
