### ISSUE TITLE
Additional Fields: Collapse button overrides other panel titles

### ISSUE THREAD

**Issue by dwasyl** [open-contracting/cove-ocds#81] opened 2020-09-28 21:22 UTC
When viewing validation results, if you try to collapse the `Additional Fields` panel, it's header and description overrides the titles and descriptions on all of the other panels. This doesn't happen when collapsing/restoring the other panels, only the `Additional Fields` panel.

As well, when there are no additional fields in use, it might be good to specify a row in that panel to say that no fields were identified rather than it just being blank as it looks like something might be missing.

**Comment by Bjwebb** [comment] 2020-09-29 15:48
I don't seem to be able to reproduce this. All the other panels stay the same for me. Could you provide your browser name and version, and some screenshots of the problem?

**Comment by dwasyl** [comment] 2020-09-29 16:05
Sure, browser is Microsoft Edge 85.0.564.51 and here are some screenshots of the various states:
**Initial state:** ![cove-initial](https://user-images.githubusercontent.com/2297074/94583582-dcc21e00-023a-11eb-82c1-7f4f864df1d8.png)

**Everything works:** ![cove-working](https://user-images.githubusercontent.com/2297074/94583579-dc298780-023a-11eb-92f8-a9b744a61a6f.png)

**Collapse Additional Fields Panel:** ![cove-error](https://user-images.githubusercontent.com/2297074/94583581-dcc21e00-023a-11eb-8dbf-65ae7ced89d2.png)

**Comment by Bjwebb** [comment] 2020-09-29 17:07
Thanks. Looks like my sample data didn't activate the "Codelist Errors" or "Additional Codelist Values" boxes, which are the ones affected.

I can reproduce now with this data fragment:
```json
{
  "version": "1.1",
  "releases": [
    {
      "additional": true,
      "id": "",
      "tag": ["invalid"],
      "tender": {"awardCriteria":"additional"}
    }
  ]
}
```

**Comment by dwasyl** [comment] 2020-09-29 17:14
I'm not sure why the Additional Fields box was even activated (considering it contains nothing...), but yeah, in finding you screenshots I noticed my other smaller didn't activate those boxes or have the same challenges. Glad you're seeing it too now!

**Comment by Bjwebb** [comment] 2020-09-30 09:33
![](https://github.trello.services/images/mini-trello-icon.png) [Small bugs](https://trello.com/c/sDE1LIkp/97-small-bugs)

**Comment by Bjwebb** [comment] 2020-09-30 13:43
This should be fixed now on https://standard.open-contracting.org/review/

**Closed by Bjwebb** 2020-09-30 13:43 UTC
